[filigran-icon][version] v0.5.1

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,17 +4,39 @@ on:
   push:
     branches:
       - main
+      - issue/*
 
 jobs:
   publish:
     runs-on: ubuntu-latest
 
+    env:
+      ACTIONS_RUNNER_DEBUG: true
+
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v4
         with:
-          node-version: '20.x'
-          registry-url: 'https://npm.pkg.github.com'
+          node-version: "20"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
 
       - name: Extract commit message
         id: extract_message
@@ -22,31 +44,32 @@ jobs:
           COMMIT_MESSAGE=$(git log -1 --pretty=%B)
           echo "commit-message=${COMMIT_MESSAGE}" >> $GITHUB_ENV
 
-      - name: Check for version number in commit message
-        id: check_version
+      - name: Check Filigran-icon
+        if: startsWith(env.commit-message, '[filigran-icon][version]')
+        run: echo "package=filigran-icon" >> $GITHUB_ENV
+
+      - name: Check Filigran-ui
+        if: startsWith(env.commit-message, '[filigran-ui][version]')
+        run: echo "package=filigran-ui" >> $GITHUB_ENV
+
+      - name: Debug output
         run: |
-          if [[ "${{ env.commit-message }}" =~ \[filigran-ui\]\s*(v[0-9]+\.[0-9]+\.[0-9]+)?$ ]]; then
-            echo "package=filigran-ui" >> $GITHUB_ENV
-            echo "version=true" >> $GITHUB_ENV
-          elif [[ "${{ env.commit-message }}" =~ \[filigran-icon\]\s*(v[0-9]+\.[0-9]+\.[0-9]+)?$ ]]; then
-            echo "package=filigran-icon" >> $GITHUB_ENV
-            echo "version=true" >> $GITHUB_ENV
-          else
-            echo "version=false" >> $GITHUB_ENV
-          fi
+          echo "Commit Message: ${{ env.commit-message }}"
+          echo "Package: ${{ env.package }}"
+          echo "Version: ${{ env.version }}"
 
       - name: Install dependencies
-        if: env.version == 'true'
-        run: npm install
+        if: env.package != ''
+        run: yarn install && npm install rimraf --global
 
       - name: Publish Filigran UI
         if: env.package == 'filigran-ui'
-        run: npm run publish:filigran-ui
+        run: yarn publish:filigran-ui
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
       - name: Publish Filigran Icon
         if: env.package == 'filigran-icon'
-        run: npm run publish:filigran-icon
+        run: yarn publish:filigran-icon
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
